#spring.application.name=api

### Configuracao JPA
### H2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

### PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.default_schema=bibliotecadb
#spring.jpa.properties.javax.persistence.create-database-schemas=true
#spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

spring.jpa.show-sql=true

# Configuracao Datasource
### H2
#spring.datasource.url=jdbc:h2:mem:bibliotecadb
# persistencia do h2 em disco
spring.datasource.url=jdbc:h2:file:/data/bibliotecadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
### Acesso ao Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

### Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

### Documentacao API Rest Swagger
### Agrupar os endpoints pela tag do Controller e ordenar os metodos
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
